/**
 * scripts/test_payu_end_to_end.js
 * 
 * Verifies that the actual PayU POST request generated by the application
 * (both standard sequence and api_version=19 sequence) succeeds against
 * PayU Production (https://secure.payu.in/_payment) with HTTP 302 redirect
 * directly to the PayU checkout page, with ZERO HTTP 403 Forbidden errors.
 */

require('dotenv').config();
const { createOrderForVideo } = require('../services/entitlement');
const { isPayUConfigured, getKey, getSalt } = require('../services/payu');

async function testPayUPostCheckout(name, apiVersion) {
  console.log(`\n======================================================`);
  console.log(`TEST: ${name}`);
  console.log(`======================================================`);

  if (!isPayUConfigured()) {
    throw new Error('PayU credentials are not configured.');
  }

  // 1. Generate payment order using the application's service
  const orderData = await createOrderForVideo({
    video_id: 41,
    user_id: 'usr_test_verification',
    email: 'customer@viralhub.com',
    phone: '9876543210',
    api_version: apiVersion,
    host: 'https://viralhub2026-mu.vercel.app',
    surl: 'https://viralhub2026-mu.vercel.app/api/payment/payu/success',
    furl: 'https://viralhub2026-mu.vercel.app/api/payment/payu/failure'
  });

  console.log(`1. Order Data generated:`);
  console.log(`   Provider: ${orderData.provider}`);
  console.log(`   Action URL: ${orderData.action}`);
  console.log(`   txnid: ${orderData.params.txnid}`);
  console.log(`   amount: ${orderData.params.amount}`);
  console.log(`   productinfo: "${orderData.params.productinfo}"`);
  console.log(`   firstname: "${orderData.params.firstname}"`);
  console.log(`   email: "${orderData.params.email}"`);
  console.log(`   phone: "${orderData.params.phone}"`);
  console.log(`   api_version: ${orderData.params.api_version || 'omitted (standard)'}`);
  console.log(`   surl: ${orderData.params.surl}`);
  console.log(`   furl: ${orderData.params.furl}`);
  console.log(`   hash length: ${orderData.params.hash.length}`);
  console.log(`   salt exposed?: ${orderData.params.salt ? 'YES (BUG!)' : 'NO (SECURE)'}`);

  // 2. Submit POST application/x-www-form-urlencoded to PayU Production
  const formBody = new URLSearchParams(orderData.params).toString();
  console.log(`\n2. Submitting POST request to ${orderData.action}...`);
  console.log(`   Content-Type: application/x-www-form-urlencoded`);
  console.log(`   Payload bytes: ${Buffer.byteLength(formBody)}`);

  const response = await fetch(orderData.action, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
    },
    body: formBody,
    redirect: 'manual'
  });

  const location = response.headers.get('location');
  console.log(`\n3. PayU Production Response:`);
  console.log(`   HTTP Status: ${response.status} ${response.statusText}`);
  console.log(`   Redirect Location: ${location || 'none'}`);

  if (response.status === 403) {
    const errorBody = await response.text();
    console.error(`   [FAILURE] PayU returned HTTP 403 Forbidden!`);
    console.error(`   Server: ${response.headers.get('server')}`);
    console.error(`   Body: ${errorBody.substring(0, 300)}`);
    throw new Error(`PayU returned 403 Forbidden!`);
  }

  if (response.status === 302 && location && location.includes('payu.in')) {
    console.log(`   [SUCCESS] PayU Production accepted the checkout request!`);
    console.log(`   [SUCCESS] User is redirected to PayU Checkout page: ${location}`);
  } else {
    const text = await response.text();
    console.log(`   Response text preview: ${text.substring(0, 300)}`);
  }

  return {
    status: response.status,
    location
  };
}

(async () => {
  try {
    const res1 = await testPayUPostCheckout('Standard PayU Checkout Request (no api_version)', undefined);
    const res2 = await testPayUPostCheckout('PayU Checkout Request with api_version=19', '19');

    console.log('\n======================================================');
    console.log('ALL PAYU PRODUCTION POST TESTS COMPLETED SUCCESSFULLY!');
    console.log('======================================================');
    process.exit(0);
  } catch (err) {
    console.error('\nTest failed:', err.message);
    process.exit(1);
  }
})();
